name: webapp github

on:
  pull_request:
    branches:
      - main  # This specifies the target branch for the pull request
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  test_java_app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          architecture: x64

      - name: Execute Tests
        run: mvn clean install
