name: webapp github

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  test_java_app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          architecture: x64

      - name: Install MySQL
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-server  # Install MySQL Server
          sudo systemctl start mysql  # Start MySQL service
          
          # Set root password and create user and database
          sudo mysql -e "CREATE USER 'raut'@'localhost' IDENTIFIED BY 'root';"
          sudo mysql -e "CREATE DATABASE cloud;"  # Create the cloud database
          sudo mysql -e "GRANT ALL PRIVILEGES ON cloud.* TO 'raut'@'localhost';"  # Grant privileges
          sudo mysql -e "FLUSH PRIVILEGES;"  # Flush privileges

      - name: Run Tests
        run: mvn clean install
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/cloud  # MySQL connection URL
          SPRING_DATASOURCE_USERNAME: raut  # MySQL username
          SPRING_DATASOURCE_PASSWORD: root  # MySQL password