name: webapp github

on:
  pull_request:
    branches:
      - main

jobs:
  test_java_app:
    runs-on: ubuntu-latest

    env:
      DB_DATABASE: test_db
      DB_USER: root
      DB_PASSWORD: root

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          architecture: x64

      - name: Start MySQL Service
        run: |
          sudo /etc/init.d/mysql start  # Start MySQL service

      - name: Create Database
        run: |
          mysql -u$DB_USER --password=$DB_PASSWORD -e "CREATE DATABASE IF NOT EXISTS $DB_DATABASE;"

      - name: Run Tests
        run: mvn clean install
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/test_db
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD: root
          
  packer_fmt_validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install Packer
        uses: hashicorp/setup-packer@v3
        with:
          version: 'latest'  

      - name: Initialize Packer
        run: packer init .
        working-directory: ./packer
  
      - name: Packer FMT
        run: packer fmt -check .
        working-directory: ./packer
  
      - name: Packer Validate
        run: packer validate .
        working-directory: ./packer