name: webapp github

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test_java_app:
    runs-on: ubuntu-latest
    services:
      mysql:  # Define the MySQL service
        image: mysql:8.0  # Use the desired version of MySQL
        env:
          MYSQL_ROOT_PASSWORD: rootpassword  # Set the root password for MySQL
          MYSQL_DATABASE: testdb  # Create a test database
          MYSQL_USER: testuser  # Create a test user
          MYSQL_PASSWORD: testpassword  # Set the password for the test user
        ports:
          - 3306:3306  # Expose MySQL on the default port
        options: >-
          --health-cmd "mysqladmin ping -h localhost -u root --silent"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          architecture: x64

      - name: Install Maven
        run: |
          sudo apt-get update
          sudo apt-get install -y maven  # Install Maven

      - name: Run Tests
        run: mvn clean install
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/testdb  # MySQL connection URL
          SPRING_DATASOURCE_USERNAME: testuser  # MySQL username
          SPRING_DATASOURCE_PASSWORD: testpassword  # MySQL password