name: webapp github

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DB_DATABASE: test_db       # Name of the database to be created
      DB_USER: root              # MySQL root user
      DB_PASSWORD: root          # MySQL root password

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start MySQL Service
        run: |
          sudo /etc/init.d/mysql start  # Start MySQL service

      - name: Create Database
        run: |
          # Use the provided root credentials (root/root)
          mysql -u$DB_USER --password=$DB_PASSWORD -e "CREATE DATABASE IF NOT EXISTS $DB_DATABASE;"

      - name: Run Tests
        run: mvn clean install
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/$DB_DATABASE  # MySQL connection URL
          SPRING_DATASOURCE_USERNAME: $DB_USER  # MySQL username
          SPRING_DATASOURCE_PASSWORD: $DB_PASSWORD  # MySQL password
