name: webapp github

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DB_DATABASE: test_db       # Name of the database to be created
      DB_USER: root              # MySQL root user
      DB_PASSWORD: root          # MySQL root password

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install MySQL
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-server  # Install MySQL Server

      - name: Start MySQL Service
        run: |
          sudo /etc/init.d/mysql start  # Start MySQL service

          
          sudo mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED BY '$DB_PASSWORD';"
          sudo mysql -e "FLUSH PRIVILEGES;"  

      - name: Create Database
        run: |
          mysql -u$DB_USER -p$DB_PASSWORD -e "CREATE DATABASE IF NOT EXISTS $DB_DATABASE;"
          
      - name: Run Tests
        run: mvn clean install
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/$DB_DATABASE
          SPRING_DATASOURCE_USERNAME: $DB_USER  
          SPRING_DATASOURCE_PASSWORD: $DB_PASSWORD  
