name: webapp github

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:  

jobs:
  test_java_app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          architecture: x64

      - name: Install MySQL
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-server  # Install MySQL Server
          sudo service mysql start  # Start MySQL service
          sudo mysql -e "CREATE DATABASE testdb;"  # Create test database
          sudo mysql -e "CREATE USER 'testuser'@'localhost' IDENTIFIED BY 'testpassword';"  # Create test user
          sudo mysql -e "GRANT ALL PRIVILEGES ON testdb.* TO 'testuser'@'localhost';"  # Grant privileges
          sudo mysql -e "FLUSH PRIVILEGES;"  # Flush privileges

      - name: Run Tests
        run: mvn clean install
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/testdb  # MySQL connection URL
          SPRING_DATASOURCE_USERNAME: testuser  # MySQL username
          SPRING_DATASOURCE_PASSWORD: testpassword  # MySQL password
