name: build-image-creation

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  build-custom-image:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    env:
      SOURCE_AMI: ${{ secrets.SOURCE_AMI }}
      SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      PROFILE: ${{ secrets.PROFILE }}
      AWS_DEVUSER: ${{ secrets.AWS_DEVUSER }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      DB_DATABASE: ${{ secrets.DB_DATABASE }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      AWS_DEMOUSER: ${{ secrets.AWS_DEMOUSER }}
      VPC_SUBNET_ID: ${{ secrets.SUBNET_ID }}
      VPC_ID: ${{ secrets.VPC_ID }}
      INSTANCE_TYPE: ${{ secrets.INSTANCE_TYPE }}

    steps:
      # 1. Checkout the repository
      - name: Checkout source code
        uses: actions/checkout@v4

      # 2. Set up JDK 21 for Maven build
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          architecture: x64

      # 3. Run integration test  
      - name: Start MySQL Service
        run: |
          sudo /etc/init.d/mysql start  # Start MySQL service

      - name: Create Database
        run: |
          mysql -u$DB_USER --password=$DB_PASSWORD -e "CREATE DATABASE IF NOT EXISTS $DB_DATABASE;"

      - name: Run Tests
        run: mvn test
        env:
          SPRING_DATASOURCE_URL: "jdbc:mysql://localhost:3306/${{ env.DB_DATABASE }}"
          SPRING_DATASOURCE_USERNAME: "${{ env.DB_USER }}"
          SPRING_DATASOURCE_PASSWORD: "${{ env.DB_PASSWORD }}" 
          AWS_S3_BUCKET_NAME: "mock-bucket"
          AWS_S3_REGION: "us-east-1"
          AWS_SNS_ARN: "test"
          DOMAIN_NAME: "dev.manalicloud.me"

      # 4. Build the application artifact
      - name: Build Maven WAR
        run: |
          mvn clean package -DskipTests
          pwd
          rm -rf imgbuild
          mkdir imgbuild && cp target/cloudproject-0.0.1-SNAPSHOT.war imgbuild   
          cp imgbuild/*.war /home/runner/work/webapp/webapp
          cd /home/runner/work/webapp/webapp && ls -all
          cd /home/runner/work/webapp/webapp/imgbuild && ls -all
          cd /home/runner/work/webapp/webapp/target && ls -all
        env:
          DB_URL: ${{ secrets.DB_URL }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

      # 6. Set up AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # 7. Setup Packer file
      - name: Setup Packer
        uses: hashicorp/setup-packer@v3
        with:
          version: "latest"

      # 8. Initialize Packer
      - name: Initialize Packer
        run: packer init .
        working-directory: ./packer

      # 9. Packer Validate
      - name: Packer Validate
        run: packer validate .
        working-directory: ./packer

      # 10. Build the custom image using Packer
      - name: Build Image
        id: build_image
        run: |
          packer build -var "aws_region=${AWS_REGION}" \
                       -var "source_ami=${SOURCE_AMI}" \
                       -var "ssh_username=${SSH_USERNAME}" \
                       -var "profile=${PROFILE}" \
                       -var "aws_demouser=${AWS_DEMOUSER}" \
                       -var "subnet_id=${VPC_SUBNET_ID}" \
                       -var "vpc_id=${VPC_ID}" \
                       -var "instance_type=${INSTANCE_TYPE}" \
                       -var "aws_devuser=${AWS_DEVUSER}" ami.pkr.hcl

          # Install jq to parse JSON data and map it to the shell variable
          sudo apt-get install jq
          ami_id=$(jq -r '.builds[-1].artifact_id' manifest.json | cut -d':' -f2)
          echo "AMI_ID=$ami_id" >> $GITHUB_ENV
          # Set the AMI ID as an output for the job
          echo "::set-output name=ami_id::$ami_id"
          echo "AMI ID: $ami_id"

        working-directory: ./packer

    outputs:
      ami_id: ${{ steps.build_image.outputs.ami_id }}

  update-launch-template-and-refresh-asg:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    needs: build-custom-image  # Ensure this job runs only after the image is built

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      LAUNCH_TEMPLATE_NAME: "csye6225_asg"
      AUTO_SCALING_GROUP_NAME: "terraform-2024111605351583800000000a"

    steps:
      # 1. Configure AWS Credentials for Launch Template
      - name: Configure AWS Credentials for Launch Template
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 2. Update the Launch Template with the new AMI ID
      - name: Update Launch Template
        run: |
          # Print the AMI ID from the build-custom-image job for debugging
          echo "AMI_ID from build-custom-image job: ${{ needs.build-custom-image.outputs.ami_id }}"
          
          # Use the AMI ID to update the launch template
          aws ec2 create-launch-template-version \
            --launch-template-name ${{ env.LAUNCH_TEMPLATE_NAME }} \
            --version-description "WebVersion2" \
            --source-version 1 \
            --launch-template-data '{"ImageId":"${{ needs.build-custom-image.outputs.ami_id }}"}'

      # 4. Trigger instance refresh on Auto Scaling Group
      - name: Trigger Instance Refresh
        run: |
          aws autoscaling start-instance-refresh \
            --auto-scaling-group-name ${{ env.AUTO_SCALING_GROUP_NAME }}

      # 5. Wait for the instance refresh to complete
      - name: Wait for Instance Refresh to Complete
        run: |
          status=$(aws autoscaling describe-instance-refreshes \
            --auto-scaling-group-name ${{ env.AUTO_SCALING_GROUP_NAME }} \
            --query 'InstanceRefreshes[0].Status' \
            --output text)
          while [[ "$status" != "Successful" && "$status" != "Failed" && "$status" != "Cancelled" ]]; do
            sleep 60
            status=$(aws autoscaling describe-instance-refreshes \
              --auto-scaling-group-name ${{ env.AUTO_SCALING_GROUP_NAME }} \
              --query 'InstanceRefreshes[0].Status' \
              --output text)
          done

          if [ "$status" == "Failed" ] || [ "$status" == "Cancelled" ]; then
            exit 1
          fi
