name: build-image-creation

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  build-custom-image:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    env:
      SOURCE_AMI: ${{ secrets.SOURCE_AMI }}
      SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      PROFILE: ${{ secrets.PROFILE }}
      AWS_DEVUSER: ${{ secrets.AWS_DEVUSER }}
      AWS_REGION: us-east-1

    steps:
      # 1. Checkout the repository
      - name: Checkout source code
        uses: actions/checkout@v4

      # 2. Set up JDK 21 for Maven build
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          architecture: x64

      # 4. Build the application artifact
      - name: Build Maven WAR
        run: mvn clean package -DskipTests
        env:
          DB_URL: ${{ secrets.DB_URL }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

      # 5. Upload the WAR file as an artifact
      - name: Upload WAR Artifact
        uses: actions/upload-artifact@v2
        with:
          name: cloudproject
          path: target/cloudproject-0.0.1-SNAPSHOT.war

      # 6. Set up AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # 7. Setup Packer
      - name: Setup Packer
        uses: hashicorp/setup-packer@v3
        with:
          version: "latest"

      # 8. Initialize Packer
      - name: Initialize Packer
        run: packer init .
        working-directory: ./packer

      # 9. Packer Validate
      - name: Packer Validate
        run: packer validate .
        working-directory: ./packer

      # 10. Build the custom image using Packer
      - name: Build Image
        run: |
          packer build -var "aws_region=${AWS_REGION}" \
                       -var "source_ami=${SOURCE_AMI}" \
                       -var "ssh_username=${SSH_USERNAME}" \
                       -var "profile=${PROFILE}" \
                       -var "aws_devuser=${AWS_DEVUSER}"
        working-directory: ./packer